### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by Kristinita** [0x4445565A/instacodes-sublimetext-plugin#2]
Please, update instacodes-sublimetext-plugin, that plugin to work correctly in 2016. Now name of service — [instaco.de](http://instaco.de/). Thanks.

**Comment by Kristinita** [comment]
I wrote a letter to the author Instaco.de, he corrected errors. Now instacodes plugin works for me. 
Thanks.

**Comment by 0x4445565A** [comment]
Ah fantastic!  I would have gotten to this issue sooner but I'm out traveling and managed to shatter my laptop screen.  Currently writing this from an old Android with a broken screen as well!  I don't travel well with electronics...

Let me know if the instaco.de updates are still broken or any other issues

**Comment by Kristinita** [comment]
@0x4445565A, when you will have the opportunity and free time, please, to change in the description of the plugin and in plugin files `Instacode.es` → `Instaco.de`. Thanks.

**Comment by 0x4445565A** [comment]
Made the changes and pushed (Also replaced the screen on my laptop, so cheers all around!)
